import { buildStreet } from './street.js';
import * as THREE from './assets/three.module.js';
const beats=[['charm','charm.mp3','#ff7a27'],['Demaris','Demaris.mp3','#e9e0d1'],['Comeback','Comeback.mp3','#bf582d'],['Yanked','Yanked.mp3','#c0b399'],['Sammy Davis Jr','SammyDavisJr.mp3','#ff963e'],['Plugitin','Plugitin.mp3','#a99c84'],['Scrooge','Scrooge.mp3','#e5cda9'],['Tender Screw (Remix)','TenderScrewRemix.mp3','#de6938']].map((b,i)=>({name:b[0],file:'../beats/'+b[1],color:b[2],slot:'ABCD'[Math.floor(i/3)]+(i%3+1)}));
const audio=new Audio();audio.preload='metadata';
const $=id=>document.getElementById(id);let selected=0,cart=[];try{cart=JSON.parse(localStorage.getItem('slowdownmoRequestsV1')||'[]');if(!Array.isArray(cart))cart=[];cart=cart.filter(x=>Number.isInteger(x.id)&&beats[x.id])}catch{}let ctx,timer,playing=false,step=0;let packages=[],machine,renderer,scene,camera,rotation=-.48,zoom=0,drag=false,moved=false,startX=0,lastX=0;
function select(i){selected=(i+beats.length)%beats.length;const b=beats[selected];$('title').textContent=b.name;$('meta').textContent=b.name.includes('(Remix)')?'REMIX / RIGHTS & AVAILABILITY BY INQUIRY':'DKTR N9NE / SLOWDOWNMO ORIGINAL';$('slot').textContent=b.slot;$('index').textContent=`${String(selected+1).padStart(2,'0')} / ${beats.length}`;$('price').textContent='INQUIRE';$('cover').style.background=b.color;$('cover').innerHTML=`<span>SLOWDOWNMO / ${b.slot}</span><b>${b.name}</b><span>DKTR N9NE · SOUND SUPPLY VOL. 001</span>`;document.querySelectorAll('.tile').forEach(el=>el.classList.toggle('selected',Number(el.dataset.id)===selected));const wasPlaying=playing;stop();audio.src=b.file;if(wasPlaying)play();packages.forEach((p,j)=>{p.position.z=j===selected?.74:.65});}
function renderTracks(filter='All'){$('tracks').innerHTML=beats.map((b,i)=>true?`<button class="tile ${i===selected?'selected':''}" data-id="${i}" aria-label="Select ${b.name}"><div class="art" style="background:${b.color}">${b.name}</div><div class="info"><div>${b.slot} / ${b.name.includes('(Remix)')?'REMIX':'BEAT'}<small>SLOWDOWNMO / DKTR N9NE</small></div><span>↗</span></div></button>`:'').join('');document.querySelectorAll('.tile').forEach(el=>el.onclick=()=>{select(+el.dataset.id);$('scene').scrollIntoView({behavior:'smooth',block:'center'})})}
function saveCart(){localStorage.setItem('slowdownmoRequestsV1',JSON.stringify(cart));$('count').textContent=cart.length;renderCart()}
function renderCart(){$('items').innerHTML=cart.length?cart.map((x,i)=>`<div class="cartitem"><div>${beats[x.id]?.name||'Beat'}<small>${x.license}</small></div><span>INQUIRY</span><button data-remove="${i}" aria-label="Remove item">×</button></div>`).join(''):'<p>Your bag is empty. Pick a sound from the machine.</p>';$('total').textContent=cart.length+' beat'+(cart.length===1?'':'s')+' selected';$('sendRequest').href='mailto:booking@slowdownmo.com?subject='+encodeURIComponent('Slowdownmo beat licensing inquiry')+'&body='+encodeURIComponent('Hi Slowdownmo,\n\nI am interested in:\n'+cart.map(x=>beats[x.id].name+' ('+x.license+')').join('\n')+'\n\nPlease share availability, licensing terms, and pricing.\n\nProject details: ');$('sendRequest').hidden=cart.length===0;document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);saveCart()})}
async function play(){try{if(!audio.src)audio.src=beats[selected].file;await audio.play();playing=true;document.body.classList.add('playing');$('play').innerHTML='Ⅱ <span>PAUSE BEAT</span><small>SLOWDOWNMO AUDIO</small>';}catch{stop();toast('Could not play this track. Try again or contact booking.')}}function stop(){audio.pause();playing=false;document.body.classList.remove('playing');$('play').innerHTML='▶ <span>LISTEN TO BEAT</span><small>SLOWDOWNMO AUDIO</small>'}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2400)}
$('wave').innerHTML=Array.from({length:45},(_,i)=>`<i style="height:${5+Math.abs(Math.sin(i*2.3))*27}px;animation-delay:${i%7/10}s"></i>`).join('');$('play').onclick=()=>playing?stop():play();$('prev').onclick=()=>select(selected-1);$('next').onclick=()=>select(selected+1);$('license').onchange=()=>{$('price').textContent='INQUIRE'};$('add').onclick=()=>{const price=+$('license').value,license=$('license').selectedOptions[0].textContent;if(cart.some(x=>x.id===selected&&x.price===price)){toast('This beat is already in your request.');return}cart.push({id:selected,price,license});saveCart();toast(beats[selected].name+' added to request');if(machine){machine.userData.dispense=performance.now()}};$('cartOpen').onclick=()=>{renderCart();$('bag').showModal()};$('closeBag').onclick=$('continue').onclick=()=>$('bag').close();$('catalog').onclick=()=>$('collection').scrollIntoView({behavior:'smooth'});$('explore').onclick=()=>{zoom=1;rotation=0;$('scene').scrollIntoView({behavior:'smooth',block:'center'})};$('reset').onclick=()=>{rotation=-.48;zoom=0};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderTracks(b.dataset.filter)});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});renderTracks();select(0);saveCart();
function texture(text,color,sub='SLOWDOWNMO'){const c=document.createElement('canvas');c.width=256;c.height=384;const g=c.getContext('2d');g.fillStyle=color;g.fillRect(0,0,256,384);g.fillStyle='#191512';g.fillRect(12,12,232,360);g.strokeStyle=color;g.lineWidth=3;g.strokeRect(22,22,212,340);g.fillStyle=color;g.font='bold 18px sans-serif';g.fillText(sub,32,50);g.font='900 42px sans-serif';text.split(' ').forEach((t,i)=>g.fillText(t,28,135+i*48,205));g.lineWidth=2;for(let i=0;i<3;i++){g.beginPath();g.arc(130,290,22+i*14,0,Math.PI*2);g.stroke()}g.font='14px monospace';g.fillText('SOUND SUPPLY / 001',30,352);return new THREE.CanvasTexture(c)}
try{const world=buildStreet($('scene'),beats);({scene,camera,renderer,machine,packages}=world);const sideTargets=world.sideTargets;
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();$('scene').addEventListener('pointerdown',e=>{drag=true;moved=false;startX=lastX=e.clientX;$('scene').setPointerCapture(e.pointerId)});$('scene').addEventListener('pointermove',e=>{if(drag){const dx=e.clientX-lastX;rotation=Math.max(-.8,Math.min(.8,rotation+dx*.006));lastX=e.clientX;if(Math.abs(e.clientX-startX)>5)moved=true}else{const rect=$('scene').getBoundingClientRect();mouse.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(mouse,camera);$('scene').style.cursor=ray.intersectObjects([...packages,...sideTargets],true).length?'pointer':'grab'}});$('scene').addEventListener('pointerup',e=>{drag=false;if(moved)return;const r=$('scene').getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects([...packages,...sideTargets],true)[0];if(hit)select(hit.object.userData.id)});$('scene').addEventListener('pointercancel',()=>drag=false);const observer=new ResizeObserver(()=>{const r=$('scene').getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()});observer.observe($('scene'));const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;function animate(t){requestAnimationFrame(animate);machine.rotation.y+=(rotation-machine.rotation.y)*.08;world.update(t,reduced);camera.position.z+=((zoom?12.6:14.4)-camera.position.z)*.05;camera.lookAt(0,.7,0);machine.children.forEach(m=>{if(m.userData.eq){const {col,row}=m.userData.eq;const height=playing?3+Math.sin(t*.009+col)*3:3+Math.sin(col*1.6)*2;m.visible=row<height}});if(machine.userData.dispense){const elapsed=t-machine.userData.dispense;if(elapsed<800)packages[selected].rotation.z=Math.sin(elapsed/800*Math.PI)*.15;else{packages[selected].rotation.z=0;machine.userData.dispense=0}}renderer.render(scene,camera)}select(0);animate(0)}catch(e){console.error(e);$('fallback').hidden=false;$('scene').hidden=true}

$('enterStore').onclick=()=>$('store').scrollIntoView({behavior:'smooth'});$('replayIntro').onclick=()=>{const film=$('brandFilm');film.currentTime=0;film.play().catch(()=>{});};if(matchMedia('(prefers-reduced-motion: reduce)').matches){$('brandFilm').pause();$('brandFilm').removeAttribute('autoplay');}

const fmt=t=>Number.isFinite(t)?Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0'):'0:00';audio.addEventListener('timeupdate',()=>{$('elapsed').textContent=fmt(audio.currentTime);$('duration').textContent=fmt(audio.duration);$('seek').value=audio.duration?audio.currentTime/audio.duration*100:0;});audio.addEventListener('loadedmetadata',()=>{$('duration').textContent=fmt(audio.duration);});audio.addEventListener('ended',()=>stop());audio.addEventListener('error',()=>{stop();toast('This track could not load. Contact booking for a preview.');});$('seek').addEventListener('input',()=>{if(Number.isFinite(audio.duration))audio.currentTime=Number($('seek').value)/100*audio.duration;});
const embedded=window.parent!==window;if(embedded)document.documentElement.classList.add('is-embedded');function resizeParent(){if(embedded)window.parent.postMessage({type:'slowdownmo-machine-height',height:Math.ceil(document.body.getBoundingClientRect().height)+2},location.origin);}new ResizeObserver(resizeParent).observe(document.body);if(embedded)window.addEventListener('message',event=>{if(event.source===window.parent&&event.origin===location.origin&&event.data?.type==='slowdownmo-machine-pause')stop();});

document.fonts.ready.then(resizeParent);
